fruitday/fruitday/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('index.urls')),
]

fruitday/index/urls.py
from django.conf.urls import url
from .views import *



urlpatterns=[
    url(r'^login/$', login_views),
    url(r'^register/$', register_views),
    url(r'^checkphone/$',checkphone_views),
    url(r'^$', index_views),
    url(r'^all_type_goods/$',all_type_goods_views),
    url(r'^check_login/$', check_login_views),
    url(r'^logout/$',logout_views),
    url(r'^add_cart/$',add_cart_views),
    url(r'^dict/$',dict_views),


]

fruitday/index/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=20)
    uphone = models.CharField(max_length=11)
    uemail = models.EmailField()
    isActive = models.BooleanField(default=True)








#商品类型
class GoodsType(models.Model):
    title = models.CharField(max_length=40)
    picture = models.ImageField(upload_to="static/upload/goodstype")
    desc = models.TextField()


    def to_dict(self):
        dic = {
            "title":self.title,
            "picture":self.picture.__str__(),
            "desc":self.desc,
        }
        return dic

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '商品类型'
        verbose_name_plural = verbose_name


#商品
class Goods(models.Model):
    title = models.CharField(max_length=40)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    spec = models.CharField(max_length=20)
    picture = models.ImageField(upload_to="static/upload/goods")
    isActive = models.BooleanField(default=True)
    #增加对商品类型的引用
    goodsType = models.ForeignKey(GoodsType,null=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name='商品'
        verbose_name_plural = verbose_name



class CartInfo(models.Model):
    #属性：user,外键，引用自Users实体
    user = models.ForeignKey(Users,null=True)
    #属性：good ,外键引用自Goods实体
    good = models.ForeignKey(Goods)
    #属性：ccount,整数，表示该商品的购买数量
    ccount = models.IntegerField()


    class Meta:
        verbose_name='购物车'
        verbose_name_plural = verbose_name

fruitday/index/templates/01_dict.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <script src="/static/js/jquery-1.11.3.js"></script>
    <script>
        $();

    </script>
</head>
<body>
    <button id="click()">发送</button>
    <div id="show">haha </div>
</body>
</html>

fruitday/index/templates/01_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <img src="{% static 'images/huiyuan.jpg'%} ">
</body>
</html>

fruitday/index/templates/index.html
<!doctype html>
<html>
 <head>
  <meta charset="UTF-8">
  <title>Document</title>
	<link rel="stylesheet" href="/static/css/index.css">
    <script src="/static/js/jquery-1.11.3.js"></script>
    <script src="/static/js/index.js"></script>
     <script src="/static/js/jquery.cookie.js"></script>

 </head>
 <body>
  <div class="container">
		<!-- 1、网页头部 -->
		<div id="top">
			<!-- 1.1 右：列表 -->
			<ul id="list">
				<li id="login-info">
					<a href="login">[登录]</a>
					,
					<a href="register">[注册有惊喜]</a>
				</li>
				<li>
					<b></b>
					果园公告
				</li>
				<li>
					<b></b>
					<a href="#">券卡兑换</a>
				</li>
				<li>
					<b></b>
					手机果园
				</li>
			</ul>
			<!-- 1.2 左：三个超链接 -->
			<!-- 1.2.1 上海 -->
			<a href="#" class="address">
				上海
				<u></u>
			</a>
			<!-- 1.2.2 满百包邮 -->
			<a>满百包邮(环郊内)</a>
			<!-- 1.2.3 星夜达 -->
			<a href="#" class="xing">星夜达</a>
		</div>
		<!-- 2、LOGO 和 热门搜索 -->
		<!-- 3、BANNER广告(横幅广告) -->
		<div id="banner">
			<img src="/static/images/banner1.jpg">
		</div>
		<!-- 4、四幅小广告 -->
		<ul id="adv-img">
			<li>
				<a href="#">
					<img src="/static/images/2ba20598135dbba5e97d241ebfa167d9.jpg">
				</a>
			</li>
			<li>
				<a href="#">
					<img src="/static/images/25af37592bf484fbeaef1cc4ff1e09c7.jpg">
				</a>
			</li>
			<li>
				<a href="#">
					<img src="/static/images/904419aa2e364412b3c07c3cbda24ef9.jpg">
				</a>
			</li>
			<li class="no-margin">
				<a href="#">
					<img src="/static/images/d72b849b461c08d991c265df00a1bfde.jpg">
				</a>
			</li>
		</ul>
		<!-- 5、网页主体内容(各种产品) -->
		<div id="main">
			<!-- 5.1 礼品卡券 -->
             {% for type in list_type %}
                <div class="item">
                    <!-- 上方:标题 + 更多-->
                    <p class="title">
                        <a href="#">更多</a>
                        <img height="42" src="/{{ type.picture }}">
                    </p>
                    <!-- 下方:内容-->
                    <ul>
                        {% for good in type.goods_set.all %}
                            <li
                                {% if forloop.counter == 5 %}
                                    class="no-margin"
                                {% endif %}
                            >
                                <!-- 上:图像 -->
                                <p>
                                    <img src="/{{ good.picture }}">
                                </p>
                                <!-- 下 ：文本 -->
                                <div class="content">
							    <!-- 右：购物车图标 -->
							    <a href="#" class="cart">
								    <img src="/static/images/cart.png">
							    </a>
							    <!-- 左上：商品名称 -->
							    <p>
								    {{ good.title}}
							    </p>
							    <!-- 左下：价格 + 规格 -->
							    <span>
								    &yen;188.00/1份
							    </span>
						        </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
			<!-- 5.2 家庭量贩 -->
			<!-- 5.3 全球鲜果 -->
			<!-- 5.4 生鲜美食 -->
		</div>
		<!-- 5、网页主体内容结束-->
		<!-- 6、网页底部 -->
	</div>
 </body>
</html>

fruitday/index/templates/login.html
{% load static %}
<!doctype html>
<head>
	<meta charset="UTF-8">
	<title>
		{% block title %}
			天天果园-登录
		{% endblock %}
	</title>
	<link rel="stylesheet" href="{% static 'css/login.css' %}">
	{% block style %}
	{% endblock %}

	{% block js %}
	{% endblock %}
</head>
<body>
	<div id="container">
		<h2>
			{% block topic %}
				会员登录
			{% endblock %}
		</h2>
		<div id="content">
			<!-- 右：登录内容 -->
			<div id="login">
				{% block form %}
				<form action="/login/" method="post">
				{% csrf_token %}
					<!-- 1、手机号 -->
					<!-- <div class="form-line"> -->
						<!-- div:承装文本框-->
						<!-- <div>
							<input type="text" name="uphone" class="form-control">
						</div>
						<!-p : 提示文字-->
						<!-- <p>手机号</p>
					</div> --> 
					<!-- 2、密码 -->
					<!-- <div class="form-line"> -->
						<!-- div:承装文本框-->
						<!-- <div>
							<input type="password" name="upwd" class="form-control">
						</div>
						<!-p : 提示文字-->
					<!-- 	<p>密码</p>
					</div> --> 
					<!-- 循环遍历form对象 -->
					{% for field in form %}
						<div class="form-line">
							<div>
								{{field}}
							</div>
							<p>
								{{field.label}}
							</p>
						</div>
					{% endfor %}
					<!-- 3、记住密码 -->
					<div class="form-line">
						<div>
							<p class="anchor">
								<a href="#">忘记密码</a>
								<a href="#">快捷登录</a>
							</p>
							<p class="saved">
								<input type="checkbox" name="isSaved">记住密码
							</p>
						</div>
					</div>
					<!-- 4、登录&会员注册 -->
					<div class="form-line">
						<div>
							<a href="/register" class="goReg">会员注册</a>
							<input type="submit" value="登录" class="btnLogin">	
						</div>
					</div>
				</form>
				{% endblock %}
			</div>
			<!-- 左：登录图片 -->
			<p id="img">
				<img src="{% static 'images/huiyuan.jpg' %}">
				{% block anchor %}
				<a href="/register">会员注册</a>
				{% endblock %}
			</p>
		</div>
	</div>
</body>
</html>

fruitday/index/templates/register.html
<!-- 继承自 login.html -->
{% extends 'login.html' %}
{% load static %}
<!-- 覆盖父模板中的同名 block -->
{% block title %}
    天天果园-注册
{% endblock %}

{% block topic %}
    注册会员
{% endblock %}

{% block anchor %}
    <a href="/login">会员登录</a>
{% endblock %}

{% block form %}
    <form id="formReg" action="/register/" method="post">
        {% csrf_token %}
        <!-- 1.手机号 -->
        <div class="form-line">
            <div>
                <input type="text" name="uphone" class="form-control">
                <p id="uphone-show">{{errMsg}}</p>
            </div>
            <p>手机号</p>
        </div>
        <!-- 2.密码-->
        <div class="form-line">
            <div>
                <input type="password" id='upwd' name="upwd" class="form-control">
            </div>
            <p>密码</p>
        </div>
        <!-- 3.确认密码-->
        <div class="form-line">
            <div>
                <input type="password" id="cpwd"  class="form-control">
            </div>
            <p>确认密码</p>
        </div>
        <!-- 4.用户名-->
        <div class="form-line">
            <div>
                <input type="text" name="uname" class="form-control" value='{{uname}}'>
            </div>
            <p>用户名</p>
        </div>
        <!-- 5.邮箱-->
        <div class="form-line">
            <div>
                <input type="text" name="uemail" class="form-control" value="{{uemail}}">
            </div>
            <p>邮箱</p>
        </div>
        <!-- 6.注册&会员登录 -->
        <div class="form-line">
            <div>
                <a href="/login" class="goReg">会员登录</a>
                <input type="submit" value="注册" class="btnLogin">
            </div>
        </div>
    </form>
{% endblock %}

{% block style %}
    <style>
        #login{
            margin-top:40px;
        }
    </style>
{% endblock %}

{% block js %}
    <script src="/static/js/jquery-1.11.3.js"></script>

    <script src="/static/js/register.js"></script>
{% endblock %}